[package]
name = "main_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_test = {path="file://../../macro_test"}
lib_test = {path="file://../../lib_test"}
bake = {path="../../../lib"}